on: [pull_request, workflow_dispatch] # TODO remove pull_request

# this cancels runs currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos-x86_64-files:
    runs-on: [macos-11] # I expect the generated files to work on macOS 12
    steps:
      - uses: actions/checkout@v3

      - run: ./ci/build_platform_w_latest_roc.sh macos_11_x86_64

      - name: Save .o files
        uses: actions/upload-artifact@v3
        with:
          name: macos-x86_64-files
          path: |
            macos-x64.o
