on: [pull_request, workflow_dispatch] # TODO remove pull_request

# this cancels runs currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-x86_64-files:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3

      - run: ./ci/build_platform_w_latest_roc.sh

      - name: Save .rh1 and .rm1 files 
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-files
          path: |
            src/linux-x86_64.rh1
            src/metadata_linux-x86_64.rm1
